# SimpleAnnounce by Refrac
# If you have suggestions put them in my discord:
# https://discord.gg/jVnmm7QnQU

# If you don't want a prefix leave this blank
Prefix: "&b&lSIMPLEANNOUNCE >> &7"
Interval: 3600 # IN SECONDS (3600 SECONDS = 1 HOUR)
# This format is if you want to announce manually with /announce <message>
# If this is disabled the command will have the Prefix instead
Format:
  ENABLED: true
  # Do you want a sound to play?
  SOUND:
    ENABLED: false
    # Sound names changes through versions so if this doesn't work then that is why
    NAME: LEVEL_UP
    # You should keep both of these the same 1.0 & 1.0, 5.0 & 5.0 etc
    VOLUME: 1.0
    PITCH: 1.0
  LINES:
    - "&8&m-------------------------------------------------"
    - "&8{arrow} &b&lSIMPLEANNOUNCE"
    - ""
    - "&8{arrow} &7{message}&7"
    - ""
    - "&8&m-------------------------------------------------"
Announcements:
  TEST:
    # Do you want a sound to play?
    SOUND:
      ENABLED: false
      # Sound names changes through versions so if this doesn't work then that is why
      NAME: LEVEL_UP
      # You should keep both of these the same 1.0 & 1.0, 5.0 & 5.0 etc
      VOLUME: 1.0
      PITCH: 1.0
    LINES:
      - "&8&m-------------------------------------------------"
      - "&8{arrow} &b&lSIMPLEANNOUNCE &8| &f&lHELLO!"
      - ""
      - "&8{arrow} &7Thank you for downloading SimpleAnnounce!"
      - "&8{arrow} &7This is the default config, edit it to your liking!"
      - ""
      - "&8{arrow} &7You can visit our discord @ &b&ndiscord.gg/jVnmm7QnQU"
      - "&8&m-------------------------------------------------"

# You will need to restart your server for these changes to work
Commands:
  ANNOUNCE:
    ENABLED: true
    PERMISSION: "simpleannounce.use"
  RELOAD:
    ENABLED: true
    PERMISSION: "simpleannounce.admin"
