name: 'SimpleAnnounce'
version: '${project.version}'
main: me.refracdevelopment.simpleannounce.spigot.SimpleAnnounce
api-version: '1.13'
softdepend:
  - 'PlaceholderAPI'
authors:
  - 'RefracDevelopment'
  - 'Refrac'
description: 'A Lightweight Announcer Plugin'
website: 'https://discord.refracdev.ml'