name: SimpleAnnounce
version: '1.3-beta.1'
main: me.refrac.simpleannounce.spigot.SimpleAnnounce
author: Refrac
description: A Lightweight Announcer Plugin
website: https://discord.gg/jVnmm7QnQU

commands:
  announce:
    description: Announce command
  announcedev:
    description: Developer command
  announcereload:
    description: Announce reload command