name: SimpleAnnounce
version: '@version@'
main: me.refracdevelopment.simpleannounce.SimpleAnnounce
author: RefracDevelopment
api-version: "1.13"
softdepend:
  - PlaceholderAPI
description: A Lightweight Automatic Announcer Plugin
website: https://discord.refracdev.ml/