name: 'SimpleAnnounce'
version: '${project.version}'
main: me.refrac.simpleannounce.spigot.SimpleAnnounce
softdepend:
  - PlaceholderAPI
author: 'Refrac'
description: 'A Lightweight Announcer Plugin'
website: 'https://discord.gg/EFeSKPg739'

commands:
  announce:
    description: 'Announce command'
  announcereload:
    description: 'Announce reload command'