name: 'SimpleAnnounce'
version: '${project.version}'
main: me.refracdevelopment.simpleannounce.spigot.SimpleAnnounce
softdepend:
  - PlaceholderAPI
authors:
  - 'RefracDevelopment'
  - 'Refrac'
description: 'A Lightweight Announcer Plugin'
website: 'https://discord.gg/EFeSKPg739'

commands:
  announce:
    description: 'Announce command'
  announcereload:
    description: 'Announce reload command'