# SimpleAnnounce by Refrac
# If you have suggestions put them in my discord:
# https://discord.gg/jVnmm7QnQU

Prefix: "&b&lSIMPLEANNOUNCE >> &7"
Interval: 3600 # IN TICKS (1200 TICKS = 1 MINUTE, 3600 TICKS = 1 HOUR)
# This format is if you want to alert manually with /alert <topic> <message>
# If this is disabled the command will be /announce <message>
Format:
  ENABLED: true
  LINES:
    - "&8&m-------------------------------------------------"
    - "&r &8{arrow} &b&lSIMPLEANNOUNCE"
    - "&r"
    - "&r &8{arrow} &7{message}"
    - "&r"
    - "&8&m-------------------------------------------------"
Announcements:
  TEST:
    SOUND:
      ENABLED: false
      NAME: LEVEL_UP
    LINES:
      - "&8&m-------------------------------------------------"
      - "&r &8{arrow} &b&lSIMPLEANNOUNCE &8| &f&lHELLO"
      - "&r"
      - "&r &8{arrow} &7Thank you for downloading SimpleAnnounce!"
      - "&r &8{arrow} &7This is the default config, edit it to your liking!"
      - "&r"
      - "&r &8{arrow} &7You can visit our discord @ &b&ndiscord.gg/jVnmm7QnQU"
      - "&8&m-------------------------------------------------"